; =========================
; 🧪 PHP DEV CONFIG
; =========================

; =========================
; 🔓 AFFICHAGE DES ERREURS
; =========================

display_errors=On
display_startup_errors=On
error_reporting=E_ALL


; =========================
; 🔍 DEBUG PHP
; =========================

; Expose PHP (utile en dev)
expose_php=On


; =========================
; ⚡ PERFORMANCES (DEV FLEXIBLE)
; =========================

memory_limit=512M

upload_max_filesize=100M
post_max_size=100M

max_execution_time=0
max_input_time=60


; =========================
; 🧠 OPCACHE (DEV MODE)
; =========================

opcache.enable=1
opcache.enable_cli=1

; IMPORTANT : on désactive le cache agressif en dev
opcache.validate_timestamps=1
opcache.revalidate_freq=0

opcache.memory_consumption=128
opcache.max_accelerated_files=10000


; =========================
; 🕒 TIMEZONE
; =========================

date.timezone=Europe/Paris


; =========================
; 📜 LOGS
; =========================

log_errors=On
error_log=/proc/self/fd/2